name: cnn-from-scratch
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytest
  - pyyaml
  - requests
  - jupyterlab
  - ipykernel
  - matplotlib
  - pytorch
  - torchvision
  - cpuonly
